### ISSUE TITLE
User wants to give and receive feedback on outfits

### ISSUE THREAD

**Issue by xinranf** [jc65536/ootd#2]
## Epic
Users want to give and receive feedback on outfits. 

## User Stories

- [x] #11 - As a user, I want to be able to rate other users’ outfit posts on a rating of 0 to 5 stars to give them my feedback 
- [x] #12 - As a user, I want to view the average rating received from other users on each of my outfit posts to know how good they are
- [x] #13 - As a user, I want to have a streak that shows how many days I have posted in a row to feel rewarded to post every day
- [x] #14 - As a user, I want to see my overall average outfit rating so I know what people think of my outfits on average
- [x] #15 - As a user, I want to see trending outfits to get inspiration for what to wear
